### ISSUE TITLE
missing country codes:

### ISSUE THREAD

**Issue by Lechus** [julien-c/iso3166#2]
'XK' => 'Kosovo',
'IC' => 'Canary Islands',

**Comment by julien-c** [comment]
Fixed

**Comment by nimasdj** [comment]
The original post array is not complete nor accurate, but if you compare that array with this comment https://gist.github.com/vxnick/380904#gistcomment-1433576 you'll see that latter is more complete and accurate, except with 'IC' => 'Canary Islands', so if you use that comment array + IC it would be good. I'd do a pull request now.
