### ISSUE TITLE
return the same instead of unknown

### ISSUE THREAD

**Issue by nimasdj** [julien-c/iso3166#3]
@julien-c I highly recommend to not return "unknown" for not found array keys, you should return just the original code input if not found. This is up to developer to check if both output/input is the same it means not found, or just show the code as it is, instead of "unknown". Your code should not change it. I hope you consider this.

**Comment by julien-c** [comment]
Hi,

I would merge a PR that does this.

Best

**Comment by nimasdj** [comment]
I did pull request not only to do that but with around more 10 ISO codes, for sure you can compare your first array with this one https://gist.github.com/vxnick/380904#gistcomment-1433576 at comment. It just needs a small indent fix if you are concerned. Then please do not forget to release a new version. btw, IC is not necessary I believe as this is not an independent country. I suggest to remove it.
