### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by araines** [julien-c/iso3166#6]
The latest changes from 1.1.0 to 1.2.0 have changed the behaviour when there are invalid country codes (from Issue #3).  Whilst my unit tests found this after upgrading the library, I wasn't expecting backward breaking changes on 1.1 -> 1.2.

I guess this is more of a suggestion than anything, but perhaps you could consider moving to semantic versioning? http://php-and-symfony.matthiasnoback.nl/2014/09/semantic-versioning-for-bundles/

The change from 1.1 -> 2.0 would have alerted me to the fact the public interface had changed :)

**Comment by nimasdj** [comment]
We apologize for the pain. This is why we did release v2 soon after that. :-)

**Comment by nimasdj** [comment]
We will delete 1.2 asap to prevent the same issue for others.

**Comment by julien-c** [comment]
Good idea, thanks.

**Comment by nimasdj** [comment]
We apologize. I deleted 1.2 to prevent the issue for others but I did not notice even 1.1 has that changes! :-( I hope all users will update to the latest version and update their coding without problem.
From now on we will keep it in mind.
